# Generated by Django 2.2.2 on 2021-02-02 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='feature_key',
            field=models.IntegerField(default=999),
        ),
    ]
