# Generated by Django 2.2.2 on 2021-02-02 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blog_feature_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='feature_key',
        ),
    ]
