# Generated by Django 2.2.2 on 2021-02-02 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smallview', '0002_album_blog_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='feature_key',
            field=models.IntegerField(default=999),
        ),
    ]
